# Generated by Django 5.1.2 on 2024-10-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('sucursal', models.CharField(max_length=200)),
                ('aspirante', models.CharField(max_length=200)),
            ],
        ),
    ]
